@startuml
class ArticleService {
    + ArticleService(dataContext:DataContext)
    + <<async>> UpdateArticleAsync(article:ArticleEntity) : Task<bool>
    + <<async>> DeleteArticleAsync(id:int) : Task<bool>
    + <<async>> GetArticleAsync(id:int) : Task<ArticleEntity>
    + <<async>> GetAllArticleAsync() : Task<IActionResult>
}
ArticleService --> "_dataContext" DataContext
@enduml
